version: '3.0'

expectations:
  population_size: 400000

actions:

  generate_study_population_allpts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_allpts
    outputs:
      highly_sensitive:
        cohort: output/input_allpts.csv
                  
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
  
  create_cohorts_allpts:
    run: stata-mp:latest analysis/001_define_covariates_allpts.do
    needs: [generate_study_population_allpts]
    outputs:
      highly_sensitive:
        log1: logs/cleaning_dataset_allpts.log 
        data1: output/data/file_eia_allpts.dta        

  create_cohorts:
    run: stata-mp:latest analysis/000_define_covariates.do
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        log1: logs/cleaning_dataset.log 
        data1: output/data/file_eia_all.dta

  run_baseline_tables_allpts:
    run: stata-mp:latest analysis/101_baseline_characteristics_allpts.do
    needs: [create_cohorts_allpts]
    outputs:
      moderately_sensitive:
        log1: logs/descriptive_tables_allpts.log      
        doc1: output/tables/baseline_allpts.csv      

  run_baseline_tables:
    run: stata-mp:latest analysis/100_baseline_characteristics.do
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/descriptive_tables.log   
        doc1: output/tables/baseline_bydiagnosis.csv   
        doc2: output/tables/baseline_byyear.csv 
        doc3: output/tables/referral_bydiag_nomiss.csv   
        doc4: output/tables/referral_byyear_nomiss.csv   
        doc5: output/tables/referral_byregion_nomiss.csv   
        doc6: output/tables/drug_bydiag_miss.csv 
        doc7: output/tables/drug_byyear_miss.csv 
        doc8: output/tables/drug_byyear_ra_miss.csv   
        doc9: output/tables/drug_byyear_psa_miss.csv
        doc10: output/tables/drug_byyear_undiff_miss.csv
        doc11: output/tables/drug_byyearanddisease.csv
        doc12: output/tables/drug_byyearandregion.csv
        doc13: output/tables/diag_count_bymonth.csv
        doc14: output/tables/appt_count_bymonth.csv
        figure1: output/figures/incidence_twoway.svg
        figure2: output/figures/incidence_twoway_appt.svg
  
  run_itsa_models:
    run: stata-mp:latest analysis/200_itsa_models.do
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/itsa_models.log   
        figure1:  output/figures/ITSA_diagnostic_delay_newey.svg
        figure2:  output/figures/ITSA_diagnostic_delay_prais.svg
        figure3:  output/figures/ITSA_diagnostic_delay_GP_newey.svg
        figure4:  output/figures/ITSA_diagnostic_delay_GP_prais.svg
        doc1: output/tables/gp_to_appt_ITSA_table.csv
  
  run_itsa_models_drugs:
    run: stata-mp:latest analysis/201_itsa_models_drugs.do
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/itsa_models_drugs.log   
        figure1:  output/figures/ITSA_csDMARD_delay_newey.svg
        figure2:  output/figures/ITSA_csDMARD_delay_prais.svg
        doc1: output/tables/appt_to_csdmard_ITSA_table.csv

  run_box_plots:
    run: stata-mp:latest analysis/300_box_plots.do
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/box_plots.log
        figure 1: output/figures/regional_qs1_bar_overall.svg
        figure 2: output/figures/regional_qs1_bar_2019.svg 
        figure 3: output/figures/regional_qs1_bar_2020.svg 
        figure 4: output/figures/regional_qs1_bar_2021.svg       
        figure 5: output/figures/regional_qs2_bar_overall.svg  
        figure 6: output/figures/regional_qs2_bar_2019.svg 
        figure 7: output/figures/regional_qs2_bar_2020.svg    
        figure 8: output/figures/regional_qs2_bar_2021.svg  
        figure 9: output/figures/regional_qs2_bar_GP_overall.svg  
        figure 10: output/figures/regional_qs2_bar_GP_2019.svg     
        figure 11: output/figures/regional_qs2_bar_GP_2020.svg 
        figure 12: output/figures/regional_qs2_bar_GP_2021.svg 
        figure 13: output/figures/regional_csdmard_bar_overall.svg  
        figure 14: output/figures/regional_csdmard_bar_2019.svg     
        figure 15: output/figures/regional_csdmard_bar_2020.svg  
 
