version: '3.0'

expectations:
  population_size: 100000

actions:

  generate_study_population_allpts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_allpts
    outputs:
      highly_sensitive:
        cohort: output/input_allpts.csv
                  
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
  
  create_cohorts_allpts:
    run: stata-mp:latest analysis/001_define_covariates_allpts.do
    needs: [generate_study_population_allpts]
    outputs:
      highly_sensitive:
        log1: logs/cleaning_dataset_allpts.smcl 
        data1: output/data/file_eia_allpts.dta        

  create_cohorts:
    run: stata-mp:latest analysis/000_define_covariates.do
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        log1: logs/cleaning_dataset.smcl 
        data1: output/data/file_eia_all.dta

  run_baseline_tables_allpts:
    run: stata-mp:latest analysis/101_baseline_characteristics_allpts.do
    needs: [create_cohorts_allpts]
    outputs:
      moderately_sensitive:
        log1: logs/descriptive_tables_allpts.smcl         

  run_baseline_tables:
    run: stata-mp:latest analysis/100_baseline_characteristics.do
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/descriptive_tables.smcl         
  
  run_itsa_models:
    run: stata-mp:latest analysis/200_itsa_models.do
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/itsa_models.smcl   
        figure1:  output/figures/ITSA_diagnostic_delay_newey.gph
        figure2:  output/figures/ITSA_diagnostic_delay_newey.svg
        figure3:  output/figures/ITSA_diagnostic_delay_prais.gph  
        figure4:  output/figures/ITSA_diagnostic_delay_prais.svg
